title: Laravel-swap
description: Currency exchange rates for Laravel and Lumen
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
gems:
  - jekyll-mentions
